import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { IBaseProps } from '@/constants/interface';
import { ToastContainer } from 'react-toastify';
import { Loading } from '@/components/ui/loading';
import 'react-toastify/dist/ReactToastify.css';
import 'react-toastify/dist/ReactToastify.min.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Home',
  description: 'Generated by create next app',
};

export default function RootLayout(props: IBaseProps) {
  return (
    <html lang='en'>
      <link rel='icon' href='/favicon.png' sizes='any' />
      <body className={inter.className} suppressHydrationWarning={true}>
        <ToastContainer />
        <Loading />
        {props.children}
      </body>
    </html>
  );
}
