export enum EnumPermission {
  PACKAGE = 'PACKAGE',
  EMPLOYEE = 'EMPLOYEE',
  CUSTOMER = 'CUSTOMER',
  COURSE = 'COURSE',
  FAQ = 'FAQ',
  TIP = 'TIP',
  NOTIFCATION = 'NOTIFCATION',
  VOUCHER = 'VOUCHER',
  PURCHASE = 'PURCHASE',
  SETTING = 'SETTING',
  FEEDBACK = 'FEEDBACK',
}
